spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQByvkkiL84jOOLI5scUvgp4ixTqvsRVtAunsomp6RM4JzfyYw8s/8DBQqF3BMGWtmeK3qYH2xL7azAg0GOl45MY9ZIFMnXQ1q2ASITqiP/ORsdUTzB012bbJmrIWrT6V30S6m2WUAYhvIi+ozTDCBFG7vvPkbgU8dJp4GIEMjE+HAaIUA5MXPnFEgnVKcaZIa/33nEI3fNnac/t/sMmmr1JBgb+HH8OwcDkj8hLYhprxJ5wK6ErdeN/3/MPBnSFLSS9Skl2tajM5FGiwrWncF2Aev/vEwsH9dSGtnHTRSJhbRn/h5Rot2aQ6Zm/PLS6HQQPCECKZCP8Gf3k/QuHA0gp3eFEFjDN99izGtTdEmjWS1EhVnC4Yk6EnwhE34zs9Ds='

token:
  expiration_time: 86400000
  secret: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==
  # secret: '{cipher}AQAsbvovHcWMzhzcRNfacegx4lc/65hwg7tmY3tYu4plz7FULE4EMrG5I4kXqDuL6SA/nW4yX7scRmcRslZuMXycoeG4V/fhv9WR32smO1FNbvx34/TNR0XPxseqcHw/KueTC9M9i63V1D/6VU9Ir7b2y2tSS6YE60tElxFG0jAbxElWnbWqCmWGA2SegSA0dWvMb44Geqj+Jz3TAAClOyCoLhNfQQlECTTbZxXVkBPVfFUi9AfI+bbvk5Y1OhhB/ZVmnyxscnyKfSE5OjSPWHwND4hYYiASlqxuOR4B/jSE7I3iwPHnw8muIMtdUKaAD0oOLtK1WOatfEDFYtD5Iywk0yGOK/x9rL+LwLM4/P/LDrdD6//OWtH6weQ7ISEQ4ZQ3HilIdTVnKhW5HfUr81OL22TtmB2MM1zuEDJJPZyN+eHZ3xDf6UjWZqzdkvLrnHA1zSKZaV0wEBXKLjEvMWV8wBlTFeqb+LGhQs1TQVDmdHmh6L/GuBf5ksesKJHGRAqOBy8rDM6BAPEFEz/mGLsNOn95xuqRuZyLQJQbH3jqXT6GA0Twjnqdg46CMArVZbHTnDFj7eXR3qt0YFZTTntepa3qs1v8BpkD7cm7z3Hzwg=='

gateway:
  # ip: 121.136.186.68
  ip: 127.0.0.1

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders